version: "3.7"

services:
  dapp-death-note-website:
    build: .
    container_name: dapp-death-note
    restart: always
    ports:
      - "3007:8080"
    command: "npm run start"
    environment:
      - VIRTUAL_HOST=deathnote.steevep.com
      - LETSENCRYPT_HOST=deathnote.steevep.com
      - LETSENCRYPT_EMAIL=steeve.payraudeau@gmail.com
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
